AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  podcast-upload-and-transcribe

  Several Lambda functions that receive a URL of a podcast file, upload it to a bucket and create a transcript of it
  that gets sent to email
Parameters:
  NotificationSourceEmailAddress:
    Type: String
  BasicAuthUsername:
    Type: String
  BasicAuthPassword:
    Type: String
Resources:
  TranscriptionsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 30
            Status: Enabled
      Tags:
        - Key: Project
          Value: podcast-upload-and-transcribe
  MediaBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Status: Enabled
      Tags:
        - Key: Project
          Value: podcast-upload-and-transcribe
  MediaBucketAccessIamUser:
    Type: AWS::IAM::User
  MediaBucketAccessIamUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:*"
            Resource:
              - !GetAtt MediaBucket.Arn
              - !Sub ${MediaBucket.Arn}/*
      PolicyName: !Sub ${AWS::StackName}-MediaBucketUploadSigningPolicy
      Users:
        - !Ref MediaBucketAccessIamUser
  MediaBucketAccessIamUserAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref MediaBucketAccessIamUser
  TranscriptionJobStartFunctionMediaBucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TranscriptionJobStartFunction.Arn
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt MediaBucket.Arn
  TranscriptionJobStartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/TranscriptionJobStartFunction/
      Description: >
        Starts transcription jobs when triggered by S3 events
      Environment:
        Variables:
          NOTIFICATION_SOURCE_EMAIL_ADDRESS: !Ref NotificationSourceEmailAddress
          TRANSCRIPTIONS_OUTPUT_BUCKET: !Ref TranscriptionsBucket
      Events:
        Mp3Created:
          Properties:
            Bucket: !Ref MediaBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mp3
          Type: S3
        Mp4Created:
          Properties:
            Bucket: !Ref MediaBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .mp4
          Type: S3
        M4aCreated:
          Properties:
            Bucket: !Ref MediaBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .m4a
          Type: S3
        WavCreated:
          Properties:
            Bucket: !Ref MediaBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .wav
          Type: S3
        FlacCreated:
          Properties:
            Bucket: !Ref MediaBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .flac
          Type: S3
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt TranscriptionJobStartFunctionIamRole.Arn
      Runtime: python3.7
      Tags:
        Project: podcast-upload-and-transcribe
      Timeout: 8
  TranscriptionJobStartFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: TranscriptionsBucketWriteAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                Resource:
                  - !GetAtt TranscriptionsBucket.Arn
                  - !Sub ${TranscriptionsBucket.Arn}/*
        - PolicyName: Transcribe
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - transcribe:GetTranscriptionJob
                  - transcribe:StartTranscriptionJob
                Resource:
                  - "*"
        - PolicyName: SESSendEmail
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource:
                  - "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  TranscriptionJobStartFunctionIamRoleMediaBucketPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:ListBucket
              - s3:GetObject
            Resource:
              - !GetAtt MediaBucket.Arn
              - !Sub ${MediaBucket.Arn}/*
      PolicyName: !Sub ${AWS::StackName}-JobStartMediaBucketReadOnly
      Roles:
        - !Ref TranscriptionJobStartFunctionIamRole
  # Transcription Job Events
  TranscriptionJobStateChangeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/TranscriptionJobStateChangeFunction/
      Description: Handles transcription job state change events
      Environment:
        Variables:
          MEDIA_BUCKET_NAME: !Ref MediaBucket
          NOTIFICATION_SOURCE_EMAIL_ADDRESS: !Ref NotificationSourceEmailAddress
      Handler: lambda_function.lambda_handler
      MemorySize: 256
      Role: !GetAtt TranscriptionJobStateChangeFunctionIamRole.Arn
      Runtime: python3.7
      Tags:
        Project: podcast-upload-and-transcribe
      Timeout: 16
  TranscriptionJobStateChangeFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: MediaBucketReadOnly
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub ${MediaBucket.Arn}/*
        - PolicyName: TranscriptionsBucketReadAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub ${TranscriptionsBucket.Arn}/*
        - PolicyName: Transcribe
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - transcribe:GetTranscriptionJob
                Resource:
                  - "*"
        - PolicyName: SESSendEmail
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ses:SendEmail
                Resource:
                  - "*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  TranscriptionJobEventsRuleLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt TranscriptionJobStateChangeFunction.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt TranscriptionJobEventsRule.Arn
  TranscriptionJobEventsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Monitors Amazon Transcribe for job state changes
      EventPattern: |
        {
          "source": [
            "aws.transcribe"
          ],
          "detail-type": [
            "Transcribe Job State Change"
          ],
          "detail": {
            "TranscriptionJobStatus": [
              "COMPLETED",
              "FAILED"
            ]
          }
        }
      State: ENABLED
      Targets:
        - Arn: !GetAtt TranscriptionJobStateChangeFunction.Arn
          Id: !Sub ${AWS::StackName}.Transcribe.JobState
  WebsiteApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref AWS::StackName
      Description: Transcription website API
  WebsiteApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: omega
      RestApiId: !Ref WebsiteApi
      DeploymentId: !Ref WebsiteApiDeployment
  WebsiteApiDeployment:
    DependsOn:
      - StaticWebsiteMethod
      - UploadToS3Method
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref WebsiteApi
  WebsiteApiUnauthorizedGatewayReponse:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      ResponseParameters:
        gatewayresponse.header.WWW-Authenticate: "'Basic'"
      ResponseType: UNAUTHORIZED
      RestApiId: !Ref WebsiteApi
      StatusCode: "401"
  StaticWebsiteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/StaticWebsiteFunction/
      Description: >
        Generates a basic front end for inputting an URL and trigger the upload to S3
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt StaticWebsiteFunctionIamRole.Arn
      Runtime: python3.7
      Tags:
        Project: podcast-upload-and-transcribe
      Timeout: 3
  StaticWebsiteFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  StaticWebsiteMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref StaticWebsiteAuthorizer
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StaticWebsiteFunction.Arn}/invocations
      ResourceId: !Ref UploadToS3Resource
      RestApiId: !Ref WebsiteApi
  StaticWebsiteMethodInvokeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt StaticWebsiteFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsiteApi}/${WebsiteApiStage}/*"
  StaticWebsiteAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/StaticWebsiteAuthorizerFunction/
      Description: >
        Authorizer for URL input form and API that triggers function which uploads to S3
      Environment:
        Variables:
          BASIC_AUTH_USERNAME: !Ref BasicAuthUsername
          BASIC_AUTH_PASSWORD: !Ref BasicAuthPassword
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt StaticWebsiteAuthorizerFunctionIamRole.Arn
      Runtime: python3.7
      Tags:
        Project: podcast-upload-and-transcribe
      Timeout: 3
  StaticWebsiteAuthorizerFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  StaticWebsiteAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerCredentials: !GetAtt StaticWebsiteAuthorizerIamRole.Arn
      AuthorizerResultTtlInSeconds: 0
      AuthorizerUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StaticWebsiteAuthorizerFunction.Arn}/invocations
      IdentitySource: method.request.header.Authorization
      Name: !Sub ${AWS::StackName}_static_website_authorizer
      RestApiId: !Ref WebsiteApi
      Type: REQUEST
  StaticWebsiteAuthorizerIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: AuthorizerLambdaInvoke
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:invokeFunction
                Resource:
                  - !GetAtt StaticWebsiteAuthorizerFunction.Arn
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  UploadToS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/UploadToS3Function/
      Description: >
        Receives the information from the form and triggers the upload to S3
      Environment:
        Variables:
          MEDIA_BUCKET: !Ref MediaBucket
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt UploadToS3FunctionIamRole.Arn
      Runtime: python3.7
      Tags:
        Project: podcast-upload-and-transcribe
      Timeout: 300
  UploadToS3FunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: MediaBucketWriteAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                  - s3:Put*
                Resource:
                  - !GetAtt MediaBucket.Arn
                  - !Sub ${MediaBucket.Arn}/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  UploadToS3Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref WebsiteApi
      ParentId: !GetAtt WebsiteApi.RootResourceId
      PathPart: upload
  UploadToS3Method:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref StaticWebsiteAuthorizer
      HttpMethod: POST
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UploadToS3Function.Arn}/invocations
      ResourceId: !Ref UploadToS3Resource
      RestApiId: !Ref WebsiteApi
  UploadToS3MethodInvokeFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt UploadToS3Function.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebsiteApi}/${WebsiteApiStage}/*"
Outputs:
  UploadWebpageUrl:
    Description: The URL for the webpage used to upload media
    Value: !Sub "https://${WebsiteApi}.execute-api.${AWS::Region}.amazonaws.com/${WebsiteApiStage}/upload"